// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLRepository.Contexts;

namespace SQLRepository.Migrations
{
    [DbContext(typeof(DiccionarioContext))]
    [Migration("20200804015902_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("SQLRepository.Entities.DiccionarioDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadDeMuestras")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FranjaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntoDestino")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntoOrigen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecorridoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tiempo")
                        .HasColumnType("REAL");

                    b.Property<int>("Unidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Diccionarios");
                });

            modelBuilder.Entity("SQLRepository.Entities.FranjaHorariaDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FinDeSemana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoraFin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoraInicio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FranjaHorarias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinDeSemana = false,
                            HoraFin = 5,
                            HoraInicio = 0
                        },
                        new
                        {
                            Id = 2,
                            FinDeSemana = false,
                            HoraFin = 7,
                            HoraInicio = 5
                        },
                        new
                        {
                            Id = 3,
                            FinDeSemana = false,
                            HoraFin = 9,
                            HoraInicio = 7
                        },
                        new
                        {
                            Id = 4,
                            FinDeSemana = false,
                            HoraFin = 11,
                            HoraInicio = 9
                        },
                        new
                        {
                            Id = 5,
                            FinDeSemana = false,
                            HoraFin = 13,
                            HoraInicio = 11
                        },
                        new
                        {
                            Id = 6,
                            FinDeSemana = false,
                            HoraFin = 15,
                            HoraInicio = 13
                        },
                        new
                        {
                            Id = 7,
                            FinDeSemana = false,
                            HoraFin = 17,
                            HoraInicio = 15
                        },
                        new
                        {
                            Id = 8,
                            FinDeSemana = false,
                            HoraFin = 19,
                            HoraInicio = 17
                        },
                        new
                        {
                            Id = 9,
                            FinDeSemana = false,
                            HoraFin = 21,
                            HoraInicio = 19
                        },
                        new
                        {
                            Id = 10,
                            FinDeSemana = false,
                            HoraFin = 24,
                            HoraInicio = 21
                        },
                        new
                        {
                            Id = 11,
                            FinDeSemana = true,
                            HoraFin = 5,
                            HoraInicio = 0
                        },
                        new
                        {
                            Id = 12,
                            FinDeSemana = true,
                            HoraFin = 12,
                            HoraInicio = 5
                        },
                        new
                        {
                            Id = 13,
                            FinDeSemana = true,
                            HoraFin = 17,
                            HoraInicio = 12
                        },
                        new
                        {
                            Id = 14,
                            FinDeSemana = true,
                            HoraFin = 24,
                            HoraInicio = 17
                        });
                });

            modelBuilder.Entity("SQLRepository.Entities.RecorridosDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Base")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Linea")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recorridos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Base = 1,
                            Linea = 500
                        },
                        new
                        {
                            Id = 2,
                            Base = 2,
                            Linea = 500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
