// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLRepository.Contexts;

namespace SQLRepository.Migrations.RegresionMultiple
{
    [DbContext(typeof(RegresionMultipleContext))]
    [Migration("20210812144602_AddRegresionDatabaset")]
    partial class AddRegresionDatabaset
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Domain.Dataset.RegresionMultiple", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("DiferenciaCeldas")
                        .HasColumnType("REAL");

                    b.Property<string>("FranjaHorariaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LineaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecorridoId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Tiempo")
                        .HasColumnType("REAL");

                    b.Property<string>("UnidadId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegresionMultipleHistorico");
                });
#pragma warning restore 612, 618
        }
    }
}
